#!/usr/bin/perl
use strict;
use warnings;


# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

my $termMin2 = 1;
my $termMin1 = 2;
my $sum = 2;
my $term = 0;
while($term <= 4000000) {
	$term = $termMin2+$termMin1;
	$termMin2 = $termMin1;
	$termMin1 = $term;
	if($term % 2 == 0) {
		$sum+=$term;
	}
}
print("Sum is $sum\n"); # 4613732